### PR TITLE
added a spot for the static weather description

### PR DESCRIPTION
**Pull request by mgaytan**

### CODE REVIEW

**Review by MoribundMedium — CHANGES_REQUESTED** [review]
Very good! I know we don't have a clear idea yet of what the app will look like, but I think it'd be best if this description is on a new line rather than on the same line as the temperature. Would you be open to the idea of putting it below by wrapping these in `<div>`s?

In addition, can you see if it's possible to modify this PR to merge to branch `FEATURE/display-local-weather` instead of `develop`?

**Comment by mgaytan** [comment]
Oops my bad! I will fix that on a new line and see if I can PR to the ``FEATURE/display-local-weather``

**Comment by mgaytan** [comment]
I'm having issues trying to push the changes I've made on ``17-static-weather-MG`` to ``FEATURE/display-local-weather``.  
I keep getting errors like this ``$ git push origin/FEATURE/display-local-weather
fatal: 'origin/FEATURE/display-local-weather' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.``

**Comment by mgaytan** [comment]
I'm not exactly sure what just happened.... It's saying the branch has conflicts but when I go to try to resolve them I'm not sure what to fix...

**Pull request merged**
